# seata所有配置, 主要关注我没有注释掉的配置, 注释掉的一般情况下默认就好
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: seata_demo_tx_group
  enable-auto-data-source-proxy: true

  service:
    vgroup-mapping:
      # seata_demo_tx_group 与 seata.tx-service-group配置 对应 !!!, 配置内容为TC集群名
      seata_demo_tx_group: default
    grouplist:
      default: 127.0.0.1:8091

  registry:
    type: nacos
    nacos:
      # server和client需要一样, 与nacos中server端的服务名一致 !!!
      application: seata-server
      server-addr: 127.0.0.1:8848
