server:
  port: 8001
spring:
  application:
    name: service-one
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        weight: 2.0
logging:
  level:
    com.alibaba.cloud.nacos.discovery: debug
