server:
  port: 9000
spring:
  application:
    name: oauth2-authorization-server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/oauth2?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: llw1123

logging:
  level:
    org.springframework.security.oauth2: debug