server:
  port: 8003
spring:
  application:
    name: service-two
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    # sentinel
#    sentinel:
#      eager: true
#      transport:
#        dashboard: localhost:8080
# 使用sentinel作为断路器
feign:
  sentinel:
    enabled: true
