server:
  port: 8002
spring:
  application:
    name: service-two
  cloud:
    nacos:
      server-addr: localhost:8848
    # sentinel
    sentinel:
      eager: true
      transport:
        dashboard: localhost:8080
# 使用sentinel作为断路器
feign:
  sentinel:
    enabled: true