server:
  port: 8888
spring:
  application:
    name: security-pure
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/spring_security?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: llw1123

logging:
  level:
    org:
      springframework:
        beans:
          factory: trace
