// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatroom.proto

package io.grpc.examples.chatroom;

public final class ChatroomProto {
  private ChatroomProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chatroom_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chatroom_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chatroom_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chatroom_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chatroom_EnterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chatroom_EnterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chatroom_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chatroom_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016chatroom.proto\022\010chatroom\"\026\n\006Person\022\014\n\004" +
      "name\030\001 \001(\t\"<\n\007Message\022\017\n\007message\030\001 \001(\t\022 " +
      "\n\006person\030\002 \001(\0132\020.chatroom.Person\" \n\rEnte" +
      "rResponse\022\017\n\007message\030\001 \001(\t\"\007\n\005Empty2\260\001\n\010" +
      "Chatroom\0224\n\005Enter\022\020.chatroom.Person\032\027.ch" +
      "atroom.EnterResponse\"\000\0223\n\013SendMessage\022\021." +
      "chatroom.Message\032\017.chatroom.Empty\"\000\0229\n\016R" +
      "eceiveMessage\022\020.chatroom.Person\032\021.chatro" +
      "om.Message\"\0000\001B,\n\031io.grpc.examples.chatr" +
      "oomB\rChatroomProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_chatroom_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_chatroom_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chatroom_Person_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_chatroom_Message_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_chatroom_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chatroom_Message_descriptor,
        new java.lang.String[] { "Message", "Person", });
    internal_static_chatroom_EnterResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_chatroom_EnterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chatroom_EnterResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_chatroom_Empty_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_chatroom_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chatroom_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
