// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatroom.proto

package io.grpc.examples.chatroom;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chatroom.Empty)
    com.google.protobuf.MessageOrBuilder {
}
