// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatroom.proto

package io.grpc.examples.chatroom;

public interface EnterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chatroom.EnterResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
