// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatroom.proto

package io.grpc.examples.chatroom;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chatroom.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.chatroom.Person person = 2;</code>
   * @return Whether the person field is set.
   */
  boolean hasPerson();
  /**
   * <code>.chatroom.Person person = 2;</code>
   * @return The person.
   */
  io.grpc.examples.chatroom.Person getPerson();
  /**
   * <code>.chatroom.Person person = 2;</code>
   */
  io.grpc.examples.chatroom.PersonOrBuilder getPersonOrBuilder();
}
