// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatroom.proto

package io.grpc.examples.chatroom;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chatroom.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
