// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification.proto

package io.grpc.examples.notice;

public interface ReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:notice.Reply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
