seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: seata_demo_tx_group
  enable-auto-data-source-proxy: true

  service:
    vgroup-mapping:
      seata_demo_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
